SERVER_PORT: ":8443"
SERVER_SSL_ENABLED: false
SERVER_PROFILING: false
SERVICE_VERSION: 1.1.1

#mysql configurations
MYSQL_USERNAME: elako_jail
MYSQL_PASSWORD: Develop@2021
DB_NAME: elako_jail
DB_DRIVER: mysql
CONNECTION_STRING: tcp(15.235.163.202:3306)/
AUTH_TOKEN: ae6ec6ca-0fba-4e27-9f81-8de1274a5ee4
RETRY_SLEEP: 3s
