SERVER_PORT: ":8443"
SERVER_SSL_ENABLED: false
SERVER_PROFILING: false

#mysql configurations
MYSQL_USERNAME: root
MYSQL_PASSWORD: Develop@2021
DB_NAME: jaildb
DB_DRIVER: mysql
CONNECTION_STRING: tcp(127.0.0.1:3306)/

RETRY_SLEEP: 3s